strict lam

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -8,9 +8,9 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.13.20211116
+# version: 0.15.20220620
 #
-# REGENDATA ("0.13.20211116",["github","cabal.project"])
+# REGENDATA ("0.15.20220620",["github","cabal.project"])
 #
 name: Haskell-CI
 on:
@@ -23,7 +23,7 @@ on:
 jobs:
   linux:
     name: Haskell-CI - Linux - ${{ matrix.compiler }}
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     timeout-minutes:
       60
     container:
@@ -32,40 +32,10 @@ jobs:
     strategy:
       matrix:
         include:
-          - compiler: ghc-9.0.1
+          - compiler: ghc-9.0.2
             compilerKind: ghc
-            compilerVersion: 9.0.1
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.10.4
-            compilerKind: ghc
-            compilerVersion: 8.10.4
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.8.4
-            compilerKind: ghc
-            compilerVersion: 8.8.4
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.6.5
-            compilerKind: ghc
-            compilerVersion: 8.6.5
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.4.4
-            compilerKind: ghc
-            compilerVersion: 8.4.4
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.2.2
-            compilerKind: ghc
-            compilerVersion: 8.2.2
-            setup-method: hvr-ppa
-            allow-failure: false
-          - compiler: ghc-8.0.2
-            compilerKind: ghc
-            compilerVersion: 8.0.2
-            setup-method: hvr-ppa
+            compilerVersion: 9.0.2
+            setup-method: ghcup
             allow-failure: false
       fail-fast: false
     steps:
@@ -73,13 +43,11 @@ jobs:
         run: |
           apt-get update
           apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common libtinfo5
-          apt-add-repository -y 'ppa:hvr/ghc'
-          apt-get update
-          apt-get install -y "$HCNAME"
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.17.3/x86_64-linux-ghcup-0.1.17.3 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.17.8/x86_64-linux-ghcup-0.1.17.8 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.6.2.0
+          "$HOME/.ghcup/bin/ghcup" install ghc "$HCVER" || (cat "$HOME"/.ghcup/logs/*.* && false)
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.6.2.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
         env:
           HCKIND: ${{ matrix.compilerKind }}
           HCNAME: ${{ matrix.compiler }}
@@ -91,10 +59,10 @@ jobs:
           echo "CABAL_DIR=$HOME/.cabal" >> "$GITHUB_ENV"
           echo "CABAL_CONFIG=$HOME/.cabal/config" >> "$GITHUB_ENV"
           HCDIR=/opt/$HCKIND/$HCVER
-          HC=$HCDIR/bin/$HCKIND
+          HC=$HOME/.ghcup/bin/$HCKIND-$HCVER
           echo "HC=$HC" >> "$GITHUB_ENV"
-          echo "HCPKG=$HCDIR/bin/$HCKIND-pkg" >> "$GITHUB_ENV"
-          echo "HADDOCK=$HCDIR/bin/haddock" >> "$GITHUB_ENV"
+          echo "HCPKG=$HOME/.ghcup/bin/$HCKIND-pkg-$HCVER" >> "$GITHUB_ENV"
+          echo "HADDOCK=$HOME/.ghcup/bin/haddock-$HCVER" >> "$GITHUB_ENV"
           echo "CABAL=$HOME/.ghcup/bin/cabal-3.6.2.0 -vnormal+nowrap" >> "$GITHUB_ENV"
           HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
           echo "HCNUMVER=$HCNUMVER" >> "$GITHUB_ENV"
@@ -158,12 +126,7 @@ jobs:
       - name: initial cabal.project for sdist
         run: |
           touch cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/staged-commons" >> cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/staged-examples" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/staged-streams" >> cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/staged-streams-resourcet" >> cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/staged-kleene" >> cabal.project
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then echo "packages: $GITHUB_WORKSPACE/source/staged-streams-unicode" >> cabal.project ; fi
           cat cabal.project
       - name: sdist
         run: |
@@ -175,46 +138,24 @@ jobs:
           find sdist -maxdepth 1 -type f -name '*.tar.gz' -exec tar -C $GITHUB_WORKSPACE/unpacked -xzvf {} \;
       - name: generate cabal.project
         run: |
-          PKGDIR_staged_commons="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-commons-[0-9.]*')"
-          echo "PKGDIR_staged_commons=${PKGDIR_staged_commons}" >> "$GITHUB_ENV"
-          PKGDIR_staged_examples="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-examples-[0-9.]*')"
-          echo "PKGDIR_staged_examples=${PKGDIR_staged_examples}" >> "$GITHUB_ENV"
           PKGDIR_staged_streams="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-streams-[0-9.]*')"
           echo "PKGDIR_staged_streams=${PKGDIR_staged_streams}" >> "$GITHUB_ENV"
-          PKGDIR_staged_streams_resourcet="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-streams-resourcet-[0-9.]*')"
-          echo "PKGDIR_staged_streams_resourcet=${PKGDIR_staged_streams_resourcet}" >> "$GITHUB_ENV"
-          PKGDIR_staged_kleene="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-kleene-[0-9.]*')"
-          echo "PKGDIR_staged_kleene=${PKGDIR_staged_kleene}" >> "$GITHUB_ENV"
-          PKGDIR_staged_streams_unicode="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/staged-streams-unicode-[0-9.]*')"
-          echo "PKGDIR_staged_streams_unicode=${PKGDIR_staged_streams_unicode}" >> "$GITHUB_ENV"
           rm -f cabal.project cabal.project.local
           touch cabal.project
           touch cabal.project.local
-          echo "packages: ${PKGDIR_staged_commons}" >> cabal.project
-          echo "packages: ${PKGDIR_staged_examples}" >> cabal.project
           echo "packages: ${PKGDIR_staged_streams}" >> cabal.project
-          echo "packages: ${PKGDIR_staged_streams_resourcet}" >> cabal.project
-          echo "packages: ${PKGDIR_staged_kleene}" >> cabal.project
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then echo "packages: ${PKGDIR_staged_streams_unicode}" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package staged-commons" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package staged-examples" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package staged-streams" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package staged-streams-resourcet" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package staged-kleene" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then echo "package staged-streams-unicode" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
+          echo "package staged-streams" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           cat >> cabal.project <<EOF
+          packages:
+            https://hackage.haskell.org/package/th-letrec-0.1/candidate/th-letrec-0.1.tar.gz
+
           allow-newer: kleene:base
           allow-newer: range-set-list:base
           allow-newer: step-function:base
           allow-newer: lattices:base
           EOF
-          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(staged-commons|staged-examples|staged-kleene|staged-streams|staged-streams-resourcet|staged-streams-unicode)$/; }' >> cabal.project.local
+          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(staged-streams)$/; }' >> cabal.project.local
           cat cabal.project
           cat cabal.project.local
       - name: dump install plan
@@ -242,21 +183,11 @@ jobs:
           $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct
       - name: cabal check
         run: |
-          cd ${PKGDIR_staged_commons} || false
-          ${CABAL} -vnormal check
-          cd ${PKGDIR_staged_examples} || false
-          ${CABAL} -vnormal check
           cd ${PKGDIR_staged_streams} || false
           ${CABAL} -vnormal check
-          cd ${PKGDIR_staged_streams_resourcet} || false
-          ${CABAL} -vnormal check
-          cd ${PKGDIR_staged_kleene} || false
-          ${CABAL} -vnormal check
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then cd ${PKGDIR_staged_streams_unicode} || false ; fi
-          if [ $((HCNUMVER >= 90000)) -ne 0 ] ; then ${CABAL} -vnormal check ; fi
       - name: haddock
         run: |
-          if [ $((HCNUMVER >= 80600)) -ne 0 ] ; then $CABAL v2-haddock $ARG_COMPILER --with-haddock $HADDOCK $ARG_TESTS $ARG_BENCH all ; fi
+          $CABAL v2-haddock --haddock-all $ARG_COMPILER --with-haddock $HADDOCK $ARG_TESTS $ARG_BENCH all
       - name: unconstrained build
         run: |
           rm -f cabal.project.local
